tap "buo/cask-upgrade"
tap "git-chglog/git-chglog"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-drivers"
tap "homebrew/cask-fonts"
tap "homebrew/cask-versions"
tap "homebrew/core"
tap "vitorgalvao/tiny-scripts"
brew "bat"
brew "diff-so-fancy"
brew "direnv"
brew "fd"
brew "fish"
brew "fzf"
brew "git"
brew "go"
brew "hub"
brew "jump"
brew "lsd"
brew "mas"
brew "neovim"
brew "nvm"
brew "ripgrep"
brew "rustup-init"
brew "starship"
brew "tealdeer"
brew "tig"
brew "trash"
brew "yadm"
brew "yarn"
brew "git-chglog/git-chglog/git-chglog"
brew "github/gh/gh"
brew "vitorgalvao/tiny-scripts/cask-repair"
cask "1password"
cask "affinity-designer-beta"
cask "affinity-photo-beta"
cask "alfred"
cask "bartender"
cask "bettertouchtool"
cask "calibre"
cask "choosy"
cask "cleanshot"
cask "discord"
cask "fantastical"
cask "figma"
cask "flux"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "google-chrome"
cask "google-drive-file-stream"
cask "gpg-suite-no-mail"
cask "iterm2"
cask "karabiner-elements"
cask "notion"
cask "nvalt"
cask "obs"
cask "rescuetime"
cask "rocket"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "zoomus"
mas "Deliveries", id: 924726344
mas "Keynote", id: 409183694
mas "NepTunes", id: 1006739057
mas "Pixave", id: 924891282
mas "Spark", id: 1176895641
mas "The Unarchiver", id: 425424353
mas "Xcode", id: 497799835
