tap "git-chglog/git-chglog"
tap "github/gh"
tap "homebrew/bundle"
tap "homebrew/cask"
tap "homebrew/cask-fonts"
tap "homebrew/core"
brew "bat"
brew "diff-so-fancy"
brew "fish"
brew "fzf"
brew "hub"
brew "jump"
brew "lsd"
brew "mas"
brew "neovim"
brew "nvm"
brew "tealdeer"
brew "tig"
brew "trash"
brew "yadm"
brew "yarn"
brew "git-chglog/git-chglog/git-chglog"
brew "github/gh/gh"
cask "1password"
cask "alfred"
cask "bartender"
cask "bettertouchtool"
cask "calibre"
cask "choosy"
cask "cleanshot"
cask "discord"
cask "fantastical"
cask "figma"
cask "flux"
cask "font-fira-code"
cask "font-fira-code-nerd-font"
cask "google-drive-file-stream"
cask "gpg-suite-no-mail"
cask "iterm2"
cask "karabiner-elements"
cask "nvalt"
cask "obs"
cask "slack"
cask "spotify"
cask "visual-studio-code"
cask "zoomus"
mas "AdGuard for Safari", id: 1440147259
mas "Deliveries", id: 924726344
mas "NepTunes", id: 1006739057
mas "Pixave", id: 924891282
mas "Spark", id: 1176895641
mas "Vimari", id: 1480933944
mas "Xcode", id: 497799835
